trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  BASE_VERSION: 1.3.5
  BUILD_NUMBER: $[counter(format('{0}_{1}', variables['BASE_VERSION'], variables['Build.SourceBranch']), 1)]
  PACKAGE_VERSION: $(BASE_VERSION).$(BUILD_NUMBER)
  CONFIGURATION: 'Release'
  BUILD_PRERELEASE: false
  CAKE_VERSION: 2.2.0

steps:
  - powershell: |
      dotnet --info
      dotnet tool install -g cake.tool --version $(CAKE_VERSION)
  - powershell: dotnet cake --configuration="$(CONFIGURATION)" --packageVersion="$(PACKAGE_VERSION)" --prerelease="$(BUILD_PRERELEASE)"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: output
      artifactName: nuget
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: diff
      artifactName: diff
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: 'Mono.ApiTools.NuGetDiff.Tests\**\*.trx'
