pool:
  vmImage: 'windows-latest'

variables:
  BUILD_NUMBER: $[counter('$(Build.SourceBranchName)_counter', 1)]
  CONFIGURATION: 'Release'
  PACKAGE_VERSION: '1.0.2.$(BUILD_NUMBER)'

steps:
  - powershell: .\build.ps1 --configuration="$(CONFIGURATION)" --packageVersion="$(PACKAGE_VERSION)"
  - task: PublishBuildArtifacts@1
    inputs:
      PathToPublish: output
      ArtifactName: nuget
